version: "3"
services:

  nginx:
    image: nginx
    container_name: nginx-es-head-smoke-watch
    
    volumes:
      - ./nginx/html/watch.smoke.eshead:/html/watch.smoke.eshead:ro
      - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro


    environment:
      VIRTUAL_HOST: eshead.smoke.watch
      LETSENCRYPT_HOST: eshead.smoke.watch
      LETSENCRYPT_EMAIL: tobias@gaszmann.de
    
    networks:
      - appnet
      - nginx-proxy
    
    expose:
      - "80"
      - "443"

    external_links:
      - docker-elasticsearch:elasticsearch

  headplugin:
    image: mobz/elasticsearch-head:5
    container_name: headplugin-elasticsearch
    
    networks:
      - appnet
      - nginx-proxy
    
    expose:
      - "9100"
      


networks:

  nginx-proxy:
    external: true

  appnet:
    external: true
      
      
  